name: Main

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/setup-mint-action@v1.0.0
        with:
          version: '0.9.0'
      - run: mint install
      - run: mint test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/setup-mint-action@v1.0.0
        with:
          version: '0.9.0'
      - run: mint install
      - name: Build
        run: mint build --skip-icons --skip-service-worker --relative
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

