name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fabasoad/setup-mint-action@v1.0.0
        with:
          version: '0.9.0'
      - run: mint install
      - run: mint test
